<?php
$z[0]=Array("global","",52,78);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",99,120);
$z[1][4]['name']="cfg_dz";
$z[2]=Array("global","",133,155);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("type"," <a href=\"[field:typelink/]\">联系我们</a> ",264,345);
$z[3][4]['typeid']="21";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",366,451);
$z[4][4]['typeid']="17";

?>